### PR TITLE
feat: Productivity Weekly(2024/05/15) @Kesin11

### PR DESCRIPTION
**Pull request by Kesin11**

### CODE REVIEW

**Comment by Kesin11** [comment]
https://github.com/korosuke613/zenn-articles/actions/runs/9268065142

```
error: Uncaught (in promise) Error: No diff found
    throw new Error("No diff found");
          ^
    at main (file:///home/runner/work/zenn-articles/zenn-articles/tools/reviewDiffWithAi.ts:34:11)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async file:///home/runner/work/zenn-articles/zenn-articles/tools/reviewDiffWithAi.ts:62:3
Error: Process completed with exit code 1.
```

> No diff found

🤔

**Comment by Kesin11** [comment]
`git diff` result will be none when base branch and forked head branch are same name.
https://github.com/korosuke613/zenn-articles/blob/2b4102551513bb42667f4b736a22b65d973966b8/.github/workflows/reusable-ai-review.yaml#L58

**Review by korosuke613 — APPROVED** [review]
LGTM!

**Pull request merged**
